# Equirectangular model for RICOH THETA S
#==============#
# Camera Model #
#==============#
Camera.name: "Theta S"
Camera.setup: "monocular"
Camera.model: "equirectangular"

Camera.fps: 30.0
Camera.cols: 1280
Camera.rows: 640

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0


Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7
Feature.mask_rectangles:
  - [0.0 ,0.525,0.58,1.0]
  - [0.0 ,0.17,0.21,1.0]
  - [0.95,1.0 ,0.38,1.0]
  - [0.25,0.30,0.50,1.0]
  - [0.80,0.85,0.75,1.00]
  - [0.60,1.00,0.70,1.00]
